// src/components/header/Header.jsx
import { useState } from 'react';
import './header.css';

const Header = () => {
	const [frst, setFrst] = useState(0);
	const [scnd, setScnd] = useState(0);

	function addHandle(ev) {
		ev.target.name === 'frst'
			? setFrst(Number(ev.target.value))
			: setScnd(Number(ev.target.value));
	}

	return (
		<header className='App-header'>
			<h1>Hello, World!</h1>
			<form action=''>
				<input type='number' name='frst' value={frst} onChange={addHandle} />
				<span>+</span>
				<input type='number' name='scnd' value={scnd} onChange={addHandle} />
			</form>
			<h3>{frst + scnd}</h3>
		</header>
	);
};

export default Header;

// src/app/header/header.component.ts
import { Component, OnInit } from '@angular/core';
import { FormControl } from '@angular/forms';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css'],
})
export class HeaderComponent implements OnInit {
  ngOnInit(): void {}

  frst: FormControl = new FormControl(0);
  scnd: FormControl = new FormControl(0);
  sum: number = this.frst.value + this.scnd.value;

  change() {
    this.sum = this.frst.value + this.scnd.value;
  }
}

<header>
  <h1>Hello, World!</h1>
  <div class="calc-container">
    <input
      type="number"
      name="frst"
      placeholder="eg. 123"
      [formControl]="frst"
      (input)="change()"
    />
    +
    <input
      type="number"
      name="scnd"
      placeholder="eg. 123"
      [formControl]="scnd"
      (input)="change()"
    />
    =
    <span>{{ sum }}</span>
  </div>
</header>
